name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install Django

      - name: Test running as standalone script
        run: | 
          python fish_django_completions.py

      - name: Test running as management command
        run: |
          python -m django startproject testproject
          cd testproject
          ./manage.py startapp testapp
          sed "s/INSTALLED_APPS = \[/INSTALLED_APPS = \['testproject.testapp',/" testproject/settings.py -i
          mkdir -p testproject/testapp/management/commands
          cp ../fish_django_completions.py testproject/testapp/management/commands
          ./manage.py fish_django_completions